// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsQ6DsOkQhsP1NdEpi97pYwXQPn-e2auc',
    appId: '1:751802777438:web:9e71adf3adebce60d199cf',
    messagingSenderId: '751802777438',
    projectId: 'event-management-57570',
    authDomain: 'event-management-57570.firebaseapp.com',
    storageBucket: 'event-management-57570.firebasestorage.app',
    measurementId: 'G-D4F6XMW1KQ',
    databaseURL: "https://event-management-57570-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOCqhpdIMH8jBEop2aSv2CxlxtbzGpM1U',
    appId: '1:751802777438:android:efcf017b8d6848d9d199cf',
    messagingSenderId: '751802777438',
    projectId: 'event-management-57570',
    storageBucket: 'event-management-57570.firebasestorage.app',
    databaseURL: "https://event-management-57570-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1L8BZE_YjayNYYZRvvvgsfYWHBjez30I',
    appId: '1:751802777438:ios:77ce1c24f51b215fd199cf',
    messagingSenderId: '751802777438',
    projectId: 'event-management-57570',
    storageBucket: 'event-management-57570.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
    databaseURL: "https://event-management-57570-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1L8BZE_YjayNYYZRvvvgsfYWHBjez30I',
    appId: '1:751802777438:ios:77ce1c24f51b215fd199cf',
    messagingSenderId: '751802777438',
    projectId: 'event-management-57570',
    storageBucket: 'event-management-57570.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
    databaseURL: "https://event-management-57570-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsQ6DsOkQhsP1NdEpi97pYwXQPn-e2auc',
    appId: '1:751802777438:web:4ccde04ed886ba0ed199cf',
    messagingSenderId: '751802777438',
    projectId: 'event-management-57570',
    authDomain: 'event-management-57570.firebaseapp.com',
    storageBucket: 'event-management-57570.firebasestorage.app',
    measurementId: 'G-TTBKVRGCM2',
    databaseURL: "https://event-management-57570-default-rtdb.firebaseio.com/"
  );
}
